version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/test-fixtures/npm-registry-signals"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "lodash"
      - dependency-name: "minimist"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action/*"
