import fs from 'fs/promises';
import path from 'path';
import https from 'https';
import os from 'os';

type SpdxLicenseEntry = {
  licenseId: string;
  isDeprecatedLicenseId?: boolean;
};

type SpdxExceptionEntry = {
  licenseExceptionId: string;
  isDeprecatedLicenseId?: boolean;
};

type SpdxLicenseList = {
  licenses?: SpdxLicenseEntry[];
};

type SpdxExceptionList = {
  exceptions?: SpdxExceptionEntry[];
};

const LICENSES_URL =
  'https://raw.githubusercontent.com/spdx/license-list-data/refs/heads/main/json/licenses.json';
const EXCEPTIONS_URL =
  'https://raw.githubusercontent.com/spdx/license-list-data/refs/heads/main/json/exceptions.json';

async function fetchJson<T>(url: string): Promise<T> {
  return new Promise((resolve, reject) => {
    const req = https.get(url, (res) => {
      const status = res.statusCode || 0;
      if (status < 200 || status > 299) {
        clearTimeout(timeout);
        reject(new Error(`Failed to fetch ${url} (${status})`));
        res.resume();
        return;
      }
      const chunks: Buffer[] = [];
      res.on('data', (d) => chunks.push(Buffer.from(d)));
      res.on('end', () => {
        clearTimeout(timeout);
        try {
          const raw = Buffer.concat(chunks).toString('utf8');
          resolve(JSON.parse(raw) as T);
        } catch (err) {
          reject(err);
        }
      });
      res.on('error', (err) => {
        clearTimeout(timeout);
        reject(err);
      });
    });
    const timeout = setTimeout(() => {
      req.destroy(new Error(`Request timed out fetching ${url}`));
      reject(new Error(`Request timed out fetching ${url}`));
    }, 10_000);
    req.on('error', (err) => {
      clearTimeout(timeout);
      reject(err);
    });
  });
}

function toSortedUnique(values: string[]): string[] {
  return Array.from(new Set(values)).sort((a, b) => a.localeCompare(b));
}

function buildSetLiteral(values: string[]): string {
  const entries = values.map((v) => `  '${v}'`).join(',\n');
  return `new Set<string>([\n${entries}\n])`;
}

async function writeSpdxFile(
  licenseIds: string[],
  deprecatedLicenseIds: string[],
  exceptionIds: string[],
  deprecatedExceptionIds: string[]
): Promise<void> {
  const filePath = path.join(__dirname, '..', 'src', 'generated', 'spdx.ts');
  const content = `// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by scripts/build-spdx.ts
// Source: SPDX license list data (licenses.json, exceptions.json)

export const SPDX_LICENSE_IDS: Set<string> = ${buildSetLiteral(licenseIds)};
export const SPDX_DEPRECATED_LICENSE_IDS: Set<string> = ${buildSetLiteral(deprecatedLicenseIds)};
export const SPDX_EXCEPTION_IDS: Set<string> = ${buildSetLiteral(exceptionIds)};
export const SPDX_DEPRECATED_EXCEPTION_IDS: Set<string> = ${buildSetLiteral(deprecatedExceptionIds)};
`;
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
}

async function main(): Promise<void> {
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'dependency-radar-spdx-'));
  try {
    const [licenses, exceptions] = await Promise.all([
      fetchJson<SpdxLicenseList>(LICENSES_URL),
      fetchJson<SpdxExceptionList>(EXCEPTIONS_URL)
    ]);

    const licenseEntries = Array.isArray(licenses.licenses) ? licenses.licenses : [];
    const exceptionEntries = Array.isArray(exceptions.exceptions) ? exceptions.exceptions : [];

    const licenseIds = toSortedUnique(
      licenseEntries.map((entry) => entry.licenseId).filter(Boolean)
    );
    const deprecatedLicenseIds = toSortedUnique(
      licenseEntries
        .filter((entry) => entry.isDeprecatedLicenseId)
        .map((entry) => entry.licenseId)
        .filter(Boolean)
    );
    const exceptionIds = toSortedUnique(
      exceptionEntries.map((entry) => entry.licenseExceptionId).filter(Boolean)
    );
    const deprecatedExceptionIds = toSortedUnique(
      exceptionEntries
        .filter((entry) => entry.isDeprecatedLicenseId)
        .map((entry) => entry.licenseExceptionId)
        .filter(Boolean)
    );

    await writeSpdxFile(licenseIds, deprecatedLicenseIds, exceptionIds, deprecatedExceptionIds);
  } finally {
    await fs.rm(tmpDir, { recursive: true, force: true });
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
