/**
 * Build script that compiles the Vite report-ui output and generates
 * TypeScript constants for embedding in the main report.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const REPORT_UI_DIST = path.join(__dirname, '../report-ui/dist');
const OUTPUT_FILE = path.join(__dirname, '../src/report-assets.ts');

function escapeForTemplateLiteral(str: string): string {
  return str
    .replace(/\\/g, '\\\\')  // Escape backslashes first
    .replace(/`/g, '\\`')    // Escape backticks
    .replace(/\$/g, '\\$');  // Escape dollar signs (for ${})
}

function main(): void {
  // Check if dist exists
  if (!fs.existsSync(REPORT_UI_DIST)) {
    console.error('Error: report-ui/dist does not exist. Run "npm run build:report-ui" first.');
    process.exit(1);
  }

  // Read the built CSS file
  const cssPath = path.join(REPORT_UI_DIST, 'report.css');
  let cssContent = '';
  if (fs.existsSync(cssPath)) {
    cssContent = fs.readFileSync(cssPath, 'utf8');
    console.log(`✓ Read CSS: ${cssPath} (${cssContent.length} bytes)`);
  } else {
    console.warn('Warning: report.css not found, CSS will be empty');
  }

  // Read the built JS file (IIFE format)
  const jsPath = path.join(REPORT_UI_DIST, 'report.iife.js');
  let jsContent = '';
  if (fs.existsSync(jsPath)) {
    jsContent = fs.readFileSync(jsPath, 'utf8');
    console.log(`✓ Read JS: ${jsPath} (${jsContent.length} bytes)`);
  } else {
    console.warn('Warning: report.iife.js not found, JS will be empty');
  }

  // Escape the content for embedding as template literals
  const escapedCss = escapeForTemplateLiteral(cssContent);
  const escapedJs = escapeForTemplateLiteral(jsContent);

  // Generate the TypeScript file
  const output = `// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by scripts/build-report.ts from report-ui build output
// To update, modify files in report-ui/ and run: npm run build:report

/**
 * CSS content for the dependency radar HTML report
 * Built from report-ui/style.css
 */
export const CSS_CONTENT = \`${escapedCss}\`;

/**
 * JavaScript content for the dependency radar HTML report
 * Built from report-ui/main.ts
 */
export const JS_CONTENT = \`${escapedJs}\`;
`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf8');
  console.log(`✓ Generated: ${OUTPUT_FILE}`);
  console.log(`  CSS: ${cssContent.length} bytes`);
  console.log(`  JS: ${jsContent.length} bytes`);
}

main();
