/**
 * Build script that compiles the Vite report-ui output and generates
 * TypeScript constants for embedding in the main report.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const REPORT_UI_DIST = path.join(__dirname, '../report-ui/dist');
const OUTPUT_FILE = path.join(__dirname, '../src/report-assets.ts');

/**
 * Escapes backslashes, backticks, and dollar signs so the input can be safely embedded in a JavaScript/TypeScript backtick template literal.
 *
 * @param str - The input string to escape
 * @returns The escaped string with `\`, `` ` ``, and `$` characters prefixed by a backslash
 */
function escapeForTemplateLiteral(str: string): string {
  return str
    .replace(/\\/g, '\\\\')  // Escape backslashes first
    .replace(/`/g, '\\`')    // Escape backticks
    .replace(/\$/g, '\\$');  // Escape dollar signs (for ${})
}

/**
 * Disambiguates minified ternary expressions that simple scanners may interpret as optional chaining.
 *
 * @param str - JavaScript source code (possibly minified)
 * @returns The input with occurrences of `?.<digit>` replaced by `? .<digit>` to make the token boundary explicit
 */
function sanitizeMinifiedJs(str: string): string {
  // Terser can emit compact ternaries like `a>b?.5:c`, which are valid but look
  // like optional chaining to simple scanners. Keep minified output while making
  // the token boundary explicit.
  return str.replace(/\?\.(\d)/g, '? .$1');
}

/**
 * Builds the embedded report assets file from the report-ui build output.
 *
 * Validates that the report-ui dist directory exists; reads `report.css` and `report.iife.js` when present, applies JS sanitization, escapes both contents for safe embedding in template literals, and writes the generated TypeScript file exporting `CSS_CONTENT` and `JS_CONTENT`. If the dist directory is missing, logs an error and exits the process with code 1.
 */
function main(): void {
  // Check if dist exists
  if (!fs.existsSync(REPORT_UI_DIST)) {
    console.error('Error: report-ui/dist does not exist. Run "npm run build:report-ui" first.');
    process.exit(1);
  }

  // Read the built CSS file. Read directly and treat a missing file as the
  // empty case rather than checking existence first (check-then-read races).
  const cssPath = path.join(REPORT_UI_DIST, 'report.css');
  let cssContent = '';
  try {
    cssContent = fs.readFileSync(cssPath, 'utf8');
    console.log(`✓ Read CSS: ${cssPath} (${cssContent.length} bytes)`);
  } catch {
    console.warn('Warning: report.css not found, CSS will be empty');
  }

  // Read the built JS file (IIFE format)
  const jsPath = path.join(REPORT_UI_DIST, 'report.iife.js');
  let jsContent = '';
  try {
    jsContent = fs.readFileSync(jsPath, 'utf8');
    jsContent = sanitizeMinifiedJs(jsContent);
    fs.writeFileSync(jsPath, jsContent, 'utf8');
    console.log(`✓ Read JS: ${jsPath} (${jsContent.length} bytes)`);
  } catch {
    console.warn('Warning: report.iife.js not found, JS will be empty');
  }

  // Escape the content for embedding as template literals
  const escapedCss = escapeForTemplateLiteral(cssContent);
  const escapedJs = escapeForTemplateLiteral(jsContent);

  // Generate the TypeScript file
  const output = `// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by scripts/build-report.ts from report-ui build output
// To update, modify files in report-ui/ and run: npm run build:report

/**
 * CSS content for the dependency radar HTML report
 * Built from report-ui/style.css
 */
export const CSS_CONTENT = \`${escapedCss}\`;

/**
 * JavaScript content for the dependency radar HTML report
 * Built from report-ui/main.ts
 */
export const JS_CONTENT = \`${escapedJs}\`;
`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf8');
  console.log(`✓ Generated: ${OUTPUT_FILE}`);
  console.log(`  CSS: ${cssContent.length} bytes`);
  console.log(`  JS: ${jsContent.length} bytes`);
}

main();
