name: OpenSSF Scorecard

on:
  push:
    branches:
      - master
  schedule:
    - cron: "22 4 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.json
          results_format: json
          publish_results: true
